/**
 * Embeds the SQL migrations from drizzle/ into lib/database/migrations.generated.ts.
 * The online edition applies them at start-up from that module, so deployment never depends on loose files
 * (a partial upload of the project can't break it). Runs automatically as part of `npm run db:generate`.
 */
import fs from "node:fs";
import path from "node:path";
import { readMigrationFiles } from "drizzle-orm/migrator";

const root = path.resolve(__dirname, "..", "..");
const migrations = readMigrationFiles({ migrationsFolder: path.join(root, "drizzle") });
const out = [
  "// AUTO-GENERATED by `npm run db:generate` (scripts/db/embed-migrations.ts) — do not edit by hand.",
  "// The database migrations from drizzle/, embedded so the online edition can migrate at start-up without reading files.",
  'import type { MigrationMeta } from "drizzle-orm/migrator";',
  "",
  `export const MIGRATIONS: MigrationMeta[] = ${JSON.stringify(migrations, null, 2)};`,
  "",
].join("\n");
const target = path.join(root, "lib", "database", "migrations.generated.ts");
fs.writeFileSync(target, out);
console.log(`Embedded ${migrations.length} migrations into ${path.relative(root, target)}`);
