// AUTO-GENERATED by `npm run db:generate` (scripts/db/embed-migrations.ts) — do not edit by hand.
// The database migrations from drizzle/, embedded so the online edition can migrate at start-up without reading files.
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: MigrationMeta[] = [
  {
    "sql": [
      "CREATE TYPE \"public\".\"document_status\" AS ENUM('pending', 'processing', 'ready', 'failed');",
      "\nCREATE TYPE \"public\".\"memory_scope\" AS ENUM('user', 'project');",
      "\nCREATE TYPE \"public\".\"message_role\" AS ENUM('system', 'user', 'assistant', 'tool');",
      "\nCREATE TYPE \"public\".\"project_member_role\" AS ENUM('owner', 'editor', 'viewer');",
      "\nCREATE TYPE \"public\".\"role\" AS ENUM('user', 'admin');",
      "\nCREATE TABLE \"accounts\" (\n\t\"user_id\" text NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"provider\" text NOT NULL,\n\t\"provider_account_id\" text NOT NULL,\n\t\"refresh_token\" text,\n\t\"access_token\" text,\n\t\"expires_at\" integer,\n\t\"token_type\" text,\n\t\"scope\" text,\n\t\"id_token\" text,\n\t\"session_state\" text,\n\tCONSTRAINT \"accounts_provider_provider_account_id_pk\" PRIMARY KEY(\"provider\",\"provider_account_id\")\n);\n",
      "\nCREATE TABLE \"attachments\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"message_id\" text,\n\t\"document_id\" text,\n\t\"file_name\" text NOT NULL,\n\t\"mime_type\" text NOT NULL,\n\t\"size_bytes\" integer NOT NULL,\n\t\"storage_key\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"attachments_storage_key_unique\" UNIQUE(\"storage_key\")\n);\n",
      "\nCREATE TABLE \"conversations\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"project_id\" text,\n\t\"title\" text DEFAULT 'New chat' NOT NULL,\n\t\"mode\" text DEFAULT 'quick' NOT NULL,\n\t\"model\" text,\n\t\"archived\" boolean DEFAULT false NOT NULL,\n\t\"pinned\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"document_chunks\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"document_id\" text NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"ordinal\" integer NOT NULL,\n\t\"content\" text NOT NULL,\n\t\"token_count\" integer DEFAULT 0 NOT NULL,\n\t\"search_vector\" \"tsvector\" GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"documents\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"project_id\" text,\n\t\"title\" text NOT NULL,\n\t\"mime_type\" text NOT NULL,\n\t\"status\" \"document_status\" DEFAULT 'pending' NOT NULL,\n\t\"error\" text,\n\t\"char_count\" integer DEFAULT 0 NOT NULL,\n\t\"chunk_count\" integer DEFAULT 0 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"error_logs\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"scope\" text NOT NULL,\n\t\"code\" text NOT NULL,\n\t\"message\" text NOT NULL,\n\t\"user_id\" text,\n\t\"request_id\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"memories\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"project_id\" text,\n\t\"scope\" \"memory_scope\" DEFAULT 'user' NOT NULL,\n\t\"content\" text NOT NULL,\n\t\"source\" text DEFAULT 'user' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"messages\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"conversation_id\" text NOT NULL,\n\t\"role\" \"message_role\" NOT NULL,\n\t\"content\" text NOT NULL,\n\t\"metadata\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"model\" text,\n\t\"provider\" text,\n\t\"input_tokens\" integer,\n\t\"output_tokens\" integer,\n\t\"latency_ms\" integer,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"model_settings\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"model_id\" text NOT NULL,\n\t\"display_name\" text NOT NULL,\n\t\"enabled\" boolean DEFAULT true NOT NULL,\n\t\"is_default\" boolean DEFAULT false NOT NULL,\n\t\"config\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"model_settings_model_id_unique\" UNIQUE(\"model_id\")\n);\n",
      "\nCREATE TABLE \"profiles\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"display_name\" text,\n\t\"bio\" text,\n\t\"timezone\" text,\n\t\"locale\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"profiles_user_id_unique\" UNIQUE(\"user_id\")\n);\n",
      "\nCREATE TABLE \"project_members\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"project_id\" text NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"role\" \"project_member_role\" DEFAULT 'viewer' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"projects\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"owner_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"instructions\" text,\n\t\"settings\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"archived\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"rate_limit_buckets\" (\n\t\"key\" text PRIMARY KEY NOT NULL,\n\t\"count\" integer DEFAULT 0 NOT NULL,\n\t\"reset_at\" timestamp with time zone NOT NULL\n);\n",
      "\nCREATE TABLE \"sessions\" (\n\t\"session_token\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"expires\" timestamp with time zone NOT NULL\n);\n",
      "\nCREATE TABLE \"system_settings\" (\n\t\"key\" text PRIMARY KEY NOT NULL,\n\t\"value\" jsonb NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"tool_calls\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"message_id\" text,\n\t\"tool_name\" text NOT NULL,\n\t\"input\" jsonb NOT NULL,\n\t\"output\" jsonb,\n\t\"success\" boolean DEFAULT true NOT NULL,\n\t\"error\" text,\n\t\"duration_ms\" integer,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"usage_records\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"model\" text,\n\t\"provider\" text,\n\t\"input_tokens\" integer DEFAULT 0 NOT NULL,\n\t\"output_tokens\" integer DEFAULT 0 NOT NULL,\n\t\"latency_ms\" integer,\n\t\"success\" boolean DEFAULT true NOT NULL,\n\t\"error_code\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"user_settings\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"theme\" text DEFAULT 'system' NOT NULL,\n\t\"default_model\" text,\n\t\"default_mode\" text DEFAULT 'quick' NOT NULL,\n\t\"memory_enabled\" boolean DEFAULT true NOT NULL,\n\t\"web_search_default\" boolean DEFAULT false NOT NULL,\n\t\"custom_instructions\" text,\n\t\"response_style\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"user_settings_user_id_unique\" UNIQUE(\"user_id\")\n);\n",
      "\nCREATE TABLE \"users\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"email_verified\" timestamp with time zone,\n\t\"name\" text,\n\t\"image\" text,\n\t\"password_hash\" text,\n\t\"role\" \"role\" DEFAULT 'user' NOT NULL,\n\t\"blocked\" boolean DEFAULT false NOT NULL,\n\t\"blocked_reason\" text,\n\t\"last_active_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"verification_tokens\" (\n\t\"identifier\" text NOT NULL,\n\t\"token\" text NOT NULL,\n\t\"expires\" timestamp with time zone NOT NULL,\n\tCONSTRAINT \"verification_tokens_identifier_token_pk\" PRIMARY KEY(\"identifier\",\"token\")\n);\n",
      "\nALTER TABLE \"accounts\" ADD CONSTRAINT \"accounts_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"attachments\" ADD CONSTRAINT \"attachments_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"attachments\" ADD CONSTRAINT \"attachments_message_id_messages_id_fk\" FOREIGN KEY (\"message_id\") REFERENCES \"public\".\"messages\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"attachments\" ADD CONSTRAINT \"attachments_document_id_documents_id_fk\" FOREIGN KEY (\"document_id\") REFERENCES \"public\".\"documents\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"conversations\" ADD CONSTRAINT \"conversations_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"conversations\" ADD CONSTRAINT \"conversations_project_id_projects_id_fk\" FOREIGN KEY (\"project_id\") REFERENCES \"public\".\"projects\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"document_chunks\" ADD CONSTRAINT \"document_chunks_document_id_documents_id_fk\" FOREIGN KEY (\"document_id\") REFERENCES \"public\".\"documents\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"document_chunks\" ADD CONSTRAINT \"document_chunks_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"documents\" ADD CONSTRAINT \"documents_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"documents\" ADD CONSTRAINT \"documents_project_id_projects_id_fk\" FOREIGN KEY (\"project_id\") REFERENCES \"public\".\"projects\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"memories\" ADD CONSTRAINT \"memories_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"memories\" ADD CONSTRAINT \"memories_project_id_projects_id_fk\" FOREIGN KEY (\"project_id\") REFERENCES \"public\".\"projects\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"messages\" ADD CONSTRAINT \"messages_conversation_id_conversations_id_fk\" FOREIGN KEY (\"conversation_id\") REFERENCES \"public\".\"conversations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"profiles\" ADD CONSTRAINT \"profiles_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"project_members\" ADD CONSTRAINT \"project_members_project_id_projects_id_fk\" FOREIGN KEY (\"project_id\") REFERENCES \"public\".\"projects\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"project_members\" ADD CONSTRAINT \"project_members_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"projects\" ADD CONSTRAINT \"projects_owner_id_users_id_fk\" FOREIGN KEY (\"owner_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"tool_calls\" ADD CONSTRAINT \"tool_calls_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"tool_calls\" ADD CONSTRAINT \"tool_calls_message_id_messages_id_fk\" FOREIGN KEY (\"message_id\") REFERENCES \"public\".\"messages\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"usage_records\" ADD CONSTRAINT \"usage_records_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"user_settings\" ADD CONSTRAINT \"user_settings_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nCREATE INDEX \"accounts_user_idx\" ON \"accounts\" USING btree (\"user_id\");",
      "\nCREATE INDEX \"attachments_user_idx\" ON \"attachments\" USING btree (\"user_id\",\"created_at\");",
      "\nCREATE INDEX \"attachments_message_idx\" ON \"attachments\" USING btree (\"message_id\");",
      "\nCREATE INDEX \"conversations_user_idx\" ON \"conversations\" USING btree (\"user_id\",\"archived\",\"updated_at\" DESC NULLS LAST);",
      "\nCREATE INDEX \"conversations_project_idx\" ON \"conversations\" USING btree (\"project_id\");",
      "\nCREATE INDEX \"conversations_title_fts\" ON \"conversations\" USING gin (to_tsvector('simple', \"title\"));",
      "\nCREATE INDEX \"chunks_document_idx\" ON \"document_chunks\" USING btree (\"document_id\",\"ordinal\");",
      "\nCREATE INDEX \"chunks_user_idx\" ON \"document_chunks\" USING btree (\"user_id\");",
      "\nCREATE INDEX \"chunks_search_idx\" ON \"document_chunks\" USING gin (\"search_vector\");",
      "\nCREATE INDEX \"documents_user_idx\" ON \"documents\" USING btree (\"user_id\",\"created_at\");",
      "\nCREATE INDEX \"documents_project_idx\" ON \"documents\" USING btree (\"project_id\");",
      "\nCREATE INDEX \"error_logs_created_idx\" ON \"error_logs\" USING btree (\"created_at\");",
      "\nCREATE INDEX \"error_logs_scope_idx\" ON \"error_logs\" USING btree (\"scope\",\"created_at\");",
      "\nCREATE INDEX \"memories_user_idx\" ON \"memories\" USING btree (\"user_id\",\"scope\");",
      "\nCREATE INDEX \"memories_project_idx\" ON \"memories\" USING btree (\"project_id\");",
      "\nCREATE INDEX \"messages_conversation_idx\" ON \"messages\" USING btree (\"conversation_id\",\"created_at\");",
      "\nCREATE INDEX \"messages_content_fts\" ON \"messages\" USING gin (to_tsvector('english', \"content\"));",
      "\nCREATE UNIQUE INDEX \"project_members_unique\" ON \"project_members\" USING btree (\"project_id\",\"user_id\");",
      "\nCREATE INDEX \"project_members_user_idx\" ON \"project_members\" USING btree (\"user_id\");",
      "\nCREATE INDEX \"projects_owner_idx\" ON \"projects\" USING btree (\"owner_id\",\"updated_at\");",
      "\nCREATE INDEX \"rate_limit_reset_idx\" ON \"rate_limit_buckets\" USING btree (\"reset_at\");",
      "\nCREATE INDEX \"tool_calls_user_idx\" ON \"tool_calls\" USING btree (\"user_id\",\"created_at\");",
      "\nCREATE INDEX \"tool_calls_message_idx\" ON \"tool_calls\" USING btree (\"message_id\");",
      "\nCREATE INDEX \"tool_calls_name_idx\" ON \"tool_calls\" USING btree (\"tool_name\",\"created_at\");",
      "\nCREATE INDEX \"usage_user_kind_idx\" ON \"usage_records\" USING btree (\"user_id\",\"kind\",\"created_at\");",
      "\nCREATE INDEX \"usage_created_idx\" ON \"usage_records\" USING btree (\"created_at\");",
      "\nCREATE INDEX \"usage_model_idx\" ON \"usage_records\" USING btree (\"model\");",
      "\nCREATE UNIQUE INDEX \"users_email_idx\" ON \"users\" USING btree (lower(\"email\"));",
      "\nCREATE INDEX \"users_created_idx\" ON \"users\" USING btree (\"created_at\");"
    ],
    "bps": true,
    "folderMillis": 1790491413955,
    "hash": "36806b724c16c1a21dea4c5db1bee48618fcca4da1738b5bbf939073072d8208"
  },
  {
    "sql": [
      "ALTER TABLE \"users\" ADD COLUMN \"session_version\" integer DEFAULT 0 NOT NULL;"
    ],
    "bps": true,
    "folderMillis": 1790493170036,
    "hash": "57fa896fcbdc9ca7d04370263d4ff222415994a9eee2e74c5459f3e9e8e0bb77"
  },
  {
    "sql": [
      "CREATE TABLE \"user_sessions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"device\" text DEFAULT 'Unknown device' NOT NULL,\n\t\"ip_prefix\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"last_seen_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"revoked_at\" timestamp with time zone,\n\t\"revoked_reason\" text\n);\n",
      "\nDROP INDEX \"conversations_title_fts\";",
      "\nDROP INDEX \"chunks_search_idx\";",
      "\nDROP INDEX \"messages_content_fts\";",
      "\nALTER TABLE \"attachments\" ADD COLUMN \"scan_status\" text DEFAULT 'pending' NOT NULL;",
      "\nALTER TABLE \"attachments\" ADD COLUMN \"scan_engine\" text;",
      "\nALTER TABLE \"attachments\" ADD COLUMN \"scanned_at\" timestamp with time zone;",
      "\nALTER TABLE \"attachments\" ADD COLUMN \"sha256\" text;",
      "\nALTER TABLE \"document_chunks\" ADD COLUMN \"search_tokens\" text[] DEFAULT '{}'::text[] NOT NULL;",
      "\nALTER TABLE \"messages\" ADD COLUMN \"search_tokens\" text[] DEFAULT '{}'::text[] NOT NULL;",
      "\nALTER TABLE \"user_sessions\" ADD CONSTRAINT \"user_sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nCREATE INDEX \"user_sessions_user_idx\" ON \"user_sessions\" USING btree (\"user_id\",\"revoked_at\");",
      "\nCREATE INDEX \"user_sessions_expires_idx\" ON \"user_sessions\" USING btree (\"expires_at\");",
      "\nCREATE INDEX \"chunks_tokens_idx\" ON \"document_chunks\" USING gin (\"search_tokens\");",
      "\nCREATE INDEX \"messages_tokens_idx\" ON \"messages\" USING gin (\"search_tokens\");",
      "\nALTER TABLE \"document_chunks\" DROP COLUMN \"search_vector\";",
      "\n-- Files uploaded before the quarantine workflow were never scanned: label them honestly.\nUPDATE \"attachments\" SET \"scan_status\" = 'unscanned' WHERE \"scan_status\" = 'pending';\n"
    ],
    "bps": true,
    "folderMillis": 1790496616721,
    "hash": "fed664f9cb6eb0817777ecbe4aac467411696b227fc3aec0a2e24f20d8bd69c9"
  },
  {
    "sql": [
      "ALTER TABLE \"users\" ADD COLUMN \"is_guest\" boolean DEFAULT false NOT NULL;",
      "\nALTER TABLE \"users\" ADD COLUMN \"guest_expires_at\" timestamp with time zone;",
      "\nCREATE INDEX \"users_guest_expiry_idx\" ON \"users\" USING btree (\"guest_expires_at\") WHERE \"users\".\"is_guest\";"
    ],
    "bps": true,
    "folderMillis": 1790499732018,
    "hash": "4d83eb5cd60ef63d1f56fab64595af455f1b6826d503b0a62b11289f3b1b767f"
  },
  {
    "sql": [
      "CREATE TABLE \"search_history\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"conversation_id\" text,\n\t\"query\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nALTER TABLE \"attachments\" ADD COLUMN \"origin\" text DEFAULT 'upload' NOT NULL;",
      "\nALTER TABLE \"search_history\" ADD CONSTRAINT \"search_history_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"search_history\" ADD CONSTRAINT \"search_history_conversation_id_conversations_id_fk\" FOREIGN KEY (\"conversation_id\") REFERENCES \"public\".\"conversations\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nCREATE INDEX \"search_history_user_idx\" ON \"search_history\" USING btree (\"user_id\",\"created_at\");"
    ],
    "bps": true,
    "folderMillis": 1790591879826,
    "hash": "e8ec3fde50a0394ab75fe50c85561980ea04a55c63bc9c8802115f2c127ba83c"
  },
  {
    "sql": [
      "CREATE TABLE \"web_vault\" (\n\t\"user_id\" text NOT NULL,\n\t\"item_id\" text NOT NULL,\n\t\"seq\" bigint NOT NULL,\n\t\"updated_at\" bigint NOT NULL,\n\t\"deleted\" boolean DEFAULT false NOT NULL,\n\t\"iv\" text NOT NULL,\n\t\"ct\" text NOT NULL,\n\t\"bytes\" integer NOT NULL,\n\tCONSTRAINT \"web_vault_user_id_item_id_pk\" PRIMARY KEY(\"user_id\",\"item_id\")\n);\n",
      "\nALTER TABLE \"users\" ADD COLUMN \"vault_salt\" text;",
      "\nALTER TABLE \"users\" ADD COLUMN \"vault_kdf_iterations\" integer;",
      "\nALTER TABLE \"web_vault\" ADD CONSTRAINT \"web_vault_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nCREATE INDEX \"web_vault_user_seq_idx\" ON \"web_vault\" USING btree (\"user_id\",\"seq\");",
      "\nCREATE SEQUENCE IF NOT EXISTS \"web_vault_seq\";\n"
    ],
    "bps": true,
    "folderMillis": 1790947712466,
    "hash": "a5944c2bb7b073450942c74c140b659d47ff264a1ebdae82b6fd2e100fbe25c3"
  }
];
