import { createCipheriv, createDecipheriv, createHmac, hkdfSync, randomBytes, timingSafeEqual } from "node:crypto";
import { ensureCloudKeys } from "./cloud-keys";

/**
 * WHITE-LOTUS field encryption service (server-only by construction: uses node:crypto, never bundled for the browser).
 *
 * ── Algorithms ──────────────────────────────────────────────────────────────────────────────
 *  • AES-256-GCM authenticated encryption, random 96-bit IV per value, 128-bit tag.
 *  • Associated data (AAD) binds each ciphertext to its owner + field ("<userId>:mem", "conv:<id>:msg" …),
 *    so a ciphertext copied into another user's row fails to decrypt.
 *  • Blind index: HMAC-SHA256 over normalised words with a separate key, so encrypted text stays searchable
 *    by exact word match without storing plaintext.
 *
 * ── Keys (never in source, Git, logs or the browser) ───────────────────────────────────────
 *  ENCRYPTION_KEYS="k2:<base64 32 bytes>,k1:<base64 32 bytes>"  first = current (encrypts), all = can decrypt.
 *  BLIND_INDEX_KEY="<base64 32 bytes>"                           stable; changing it requires `npm run data:encrypt -- --reindex`.
 *  Local install: generated on first run and kept in the config folder, apart from the data (lib/local/keys.ts;
 *  Windows DPAPI when available). The launcher passes them to the app; the app refuses to start without them.
 *
 * ── Format ──────────────────────────────────────────────────────────────────────────────────
 *  "enc:v1:<keyId>:<base64url(iv | tag | ciphertext)>"
 *  Values without the prefix are legacy plaintext and are returned unchanged (so encryption can be enabled on an
 *  existing database, then `npm run data:encrypt` converts the old rows).
 */
const PREFIX = "enc:v1:";
const KEY_ID = /^[a-zA-Z0-9_-]{1,16}$/;

export type EncryptionKey = { id: string; key: Buffer };

export class EncryptionConfigError extends Error {}

/** Parse and validate ENCRYPTION_KEYS. Throws EncryptionConfigError with an actionable message. */
export function parseKeys(raw: string | undefined): EncryptionKey[] {
  if (!raw) return [];
  const seen = new Set<string>();
  const entries = raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  return entries
    .map((entry) => {
      // A single bare key (e.g. generated by the host's "generate value" feature) is key id "k1".
      if (entries.length === 1 && !entry.includes(":")) entry = `k1:${entry}`;
      const i = entry.indexOf(":");
      if (i <= 0) throw new EncryptionConfigError("ENCRYPTION_KEYS entries must look like <id>:<base64 key>");
      const id = entry.slice(0, i);
      if (!KEY_ID.test(id)) throw new EncryptionConfigError(`Invalid encryption key id '${id}'`);
      if (seen.has(id)) throw new EncryptionConfigError(`Duplicate encryption key id '${id}'`);
      seen.add(id);
      const key = Buffer.from(entry.slice(i + 1), "base64");
      if (key.length !== 32) throw new EncryptionConfigError(`Encryption key '${id}' must be 32 bytes (base64). Generate: npm run keys:generate`);
      if (key.every((b) => b === key[0])) throw new EncryptionConfigError(`Encryption key '${id}' is not random`);
      return { id, key };
    });
}

let cachedRaw: string | undefined;
let cachedKeys: EncryptionKey[] = [];
function keys(): EncryptionKey[] {
  ensureCloudKeys();
  const raw = process.env.ENCRYPTION_KEYS;
  if (raw !== cachedRaw) {
    cachedKeys = parseKeys(raw);
    cachedRaw = raw;
  }
  return cachedKeys;
}

export function encryptionEnabled() {
  return keys().length > 0;
}

/** Validate configuration at startup (called from config/env.ts in production). */
export function assertEncryptionConfigured() {
  if (!keys().length) throw new EncryptionConfigError("ENCRYPTION_KEYS is required in production");
  blindIndexKey(true);
}

export function encrypt(plain: string, aad: string): string {
  const k = keys()[0];
  if (!k) {
    if (process.env.NODE_ENV === "production") throw new EncryptionConfigError("ENCRYPTION_KEYS is required in production");
    return plain; // local development without keys: stored as plaintext (clearly marked by the missing prefix)
  }
  const iv = randomBytes(12);
  const c = createCipheriv("aes-256-gcm", k.key, iv);
  c.setAAD(Buffer.from(aad));
  const ct = Buffer.concat([c.update(plain, "utf8"), c.final()]);
  return `${PREFIX}${k.id}:${Buffer.concat([iv, c.getAuthTag(), ct]).toString("base64url")}`;
}

export function decrypt(value: string | null | undefined, aad: string): string {
  if (value == null) return "";
  if (!value.startsWith(PREFIX)) return value; // legacy plaintext
  const rest = value.slice(PREFIX.length);
  const i = rest.indexOf(":");
  const k = keys().find((x) => x.id === rest.slice(0, i));
  if (!k) throw new EncryptionConfigError("Encrypted value uses an unknown key id — is ENCRYPTION_KEYS complete?");
  const buf = Buffer.from(rest.slice(i + 1), "base64url");
  if (buf.length < 28) throw new Error("Malformed ciphertext");
  const d = createDecipheriv("aes-256-gcm", k.key, buf.subarray(0, 12));
  d.setAAD(Buffer.from(aad));
  d.setAuthTag(buf.subarray(12, 28));
  return Buffer.concat([d.update(buf.subarray(28)), d.final()]).toString("utf8");
}

// ─────────────────────────── File bytes ───────────────────────────
// Local files are encrypted too: "WLF1" | keyIdLen(1) | keyId | iv(12) | tag(16) | ciphertext.
// AAD = the storage key, so a file can't be swapped for another user's file on disk.
const FILE_MAGIC = Buffer.from("WLF1");

export function encryptBytes(data: Buffer, aad: string): Buffer {
  const k = keys()[0];
  if (!k) {
    if (process.env.NODE_ENV === "production") throw new EncryptionConfigError("ENCRYPTION_KEYS is required in production");
    return data;
  }
  const iv = randomBytes(12);
  const c = createCipheriv("aes-256-gcm", k.key, iv);
  c.setAAD(Buffer.from(aad));
  const ct = Buffer.concat([c.update(data), c.final()]);
  const id = Buffer.from(k.id);
  return Buffer.concat([FILE_MAGIC, Buffer.from([id.length]), id, iv, c.getAuthTag(), ct]);
}

export function decryptBytes(data: Buffer, aad: string): Buffer {
  if (data.length < 5 || !data.subarray(0, 4).equals(FILE_MAGIC)) return data; // stored before encryption was enabled
  const idLen = data[4];
  const id = data.subarray(5, 5 + idLen).toString();
  const k = keys().find((x) => x.id === id);
  if (!k) throw new EncryptionConfigError("Encrypted file uses an unknown key id — is ENCRYPTION_KEYS complete?");
  const off = 5 + idLen;
  const d = createDecipheriv("aes-256-gcm", k.key, data.subarray(off, off + 12));
  d.setAAD(Buffer.from(aad));
  d.setAuthTag(data.subarray(off + 12, off + 28));
  return Buffer.concat([d.update(data.subarray(off + 28)), d.final()]);
}

/** Decrypt, returning a safe placeholder instead of throwing (for list views; the failure is still logged by callers). */
export function decryptOr(value: string | null | undefined, aad: string, fallback = "[unreadable — check encryption keys]"): string {
  try {
    return decrypt(value, aad);
  } catch {
    return fallback;
  }
}

export const encryptNullable = (v: string | null | undefined, aad: string) => (v == null || v === "" ? (v ?? null) : encrypt(v, aad));
export const isEncrypted = (v: string | null | undefined) => Boolean(v?.startsWith(PREFIX));
export const currentKeyId = () => keys()[0]?.id ?? null;

/** Encrypt a JSON value into a { _enc } envelope (used for message metadata: sources, search queries, activity). */
export function encryptJson(value: unknown, aad: string): Record<string, unknown> {
  if (!encryptionEnabled() && process.env.NODE_ENV !== "production") return (value ?? {}) as Record<string, unknown>;
  return { _enc: encrypt(JSON.stringify(value ?? {}), aad) };
}
export function decryptJson<T = Record<string, unknown>>(value: unknown, aad: string): T {
  if (value && typeof value === "object" && typeof (value as { _enc?: unknown })._enc === "string") {
    try {
      return JSON.parse(decrypt((value as { _enc: string })._enc, aad)) as T;
    } catch {
      return {} as T;
    }
  }
  return (value ?? {}) as T;
}

// ─────────────────────────── Blind index (searchable encryption) ───────────────────────────

let cachedIndexKey: Buffer | null | undefined;
let cachedIndexRaw: string | undefined;
function blindIndexKey(required = false): Buffer | null {
  ensureCloudKeys();
  const raw = process.env.BLIND_INDEX_KEY;
  if (raw !== cachedIndexRaw || cachedIndexKey === undefined) {
    cachedIndexRaw = raw;
    if (raw) {
      const k = Buffer.from(raw, "base64");
      if (k.length !== 32) throw new EncryptionConfigError("BLIND_INDEX_KEY must be 32 bytes (base64). Generate: npm run keys:generate");
      // Domain-separated subkey, so the raw secret is never used directly.
      cachedIndexKey = Buffer.from(hkdfSync("sha256", k, Buffer.alloc(0), "white-lotus:blind-index:v1", 32));
    } else cachedIndexKey = null;
  }
  if (!cachedIndexKey && (required || process.env.NODE_ENV === "production")) throw new EncryptionConfigError("BLIND_INDEX_KEY is required in production");
  return cachedIndexKey;
}

const STOP = new Set(
  "a an and are as at be but by for from has have he her his i in is it its of on or our she that the their them they this to was we were what when where which who will with you your not no do does did can could would should shall may might must been being into than then there these those about after before also any".split(" "),
);

/** Normalise text into search words: lowercase, strip accents, split, drop stop-words, light stemming. */
export function searchWords(text: string, max = 2000): string[] {
  const out = new Set<string>();
  const words = text
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .split(/[^\p{L}\p{N}]+/u);
  for (let w of words) {
    if (w.length < 2 || w.length > 40 || STOP.has(w)) continue;
    if (w.length > 5) w = w.replace(/(ingly|edly|ing|ed|ly|es|s)$/, "");
    else if (w.length > 3) w = w.replace(/s$/, "");
    out.add(w);
    if (out.size >= max) break;
  }
  return [...out];
}

/** HMAC tokens for a text (stored in search_tokens text[] with a GIN index). Plain words in dev without a key. */
export function blindTokens(text: string, max = 2000): string[] {
  const key = blindIndexKey();
  const words = searchWords(text, max);
  if (!key) return words; // development only
  return words.map((w) => createHmac("sha256", key).update(w).digest("base64url").slice(0, 16));
}

// ─────────────────────────── URL signing ───────────────────────────

function signingKey() {
  const s = process.env.AUTH_SECRET;
  if (!s) throw new EncryptionConfigError("AUTH_SECRET is not set");
  return Buffer.from(hkdfSync("sha256", Buffer.from(s), Buffer.alloc(0), "white-lotus:url-signing:v1", 32));
}
export function sign(payload: string): string {
  return createHmac("sha256", signingKey()).update(payload).digest("base64url");
}
export function verifySignature(payload: string, sig: string): boolean {
  const a = Buffer.from(sign(payload));
  const b = Buffer.from(sig);
  return a.length === b.length && timingSafeEqual(a, b);
}
